### ISSUE TITLE
Gem rgeo-kml not found on https://rubygems.org

### ISSUE THREAD

**Issue by Neoteddy** [ldonnet/rgeo-kml#2]
Hi!
I would like to use the rgeo-kml gem but it seems like it is not available on https://rubygems.org.

When gem install rgeo-kml :
ERROR:  Could not find a valid gem 'rgeo-kml' (>= 0) in any repository

Please, is it possible to make it available for the community?

**Comment by denishaskin** [comment]
@Neoteddy until this gets published, if you're using bundler you can install it from github:

```
gem 'rgeo-kml', git: 'git://github.com/ldonnet/rgeo-kml.git'
```

Alternatively, of course, you can clone the repo and install from there.  But @ldonnet either it should be published or the README corrected.

**Comment by Neoteddy** [comment]
ok i'll do it.
thank you for your reply!

**Comment by ldonnet** [comment]
Thanks @denishaskin to help @Neoteddy. I relase the first version of the gem today.
You could now access rgeo-kml in rubygems.
